data:
  class_path: litgpt.data.TextFiles
  init_args:
    train_data_path: data/
devices: auto
eval:
  final_validation: false
  initial_validation: false
  interval: 200
  max_iters: 100
  max_new_tokens: null
initial_checkpoint_dir: null
logger_name: csv
model_config:
  bias: false
  block_size: 500
  head_size: 16
  hf_config: {}
  intermediate_size: 1024
  mlp_class_name: LLaMAMLP
  n_embd: 512
  n_head: 8
  n_layer: 4
  n_query_groups: 1
  name: counting_ones
  norm_class_name: RMSNorm
  padded_vocab_size: 50304
  parallel_residual: false
  rotary_percentage: 1.0
  scale_embeddings: false
model_name: counting_ones
num_nodes: 1
optimizer:
  class_path: torch.optim.AdamW
  init_args:
    betas:
    - 0.9
    - 0.95
    lr: 0.00005
    weight_decay: 0.1
out_dir: model/
precision: bf16-mixed
resume: false
seed: 42
tokenizer_dir: tokenizer/
train:
  epochs: null
  global_batch_size: 16
  log_interval: 50
  lr_warmup_steps: 0
  max_norm: 1.0
  max_seq_length: 500
  max_steps: null
  max_tokens: 40000000
  micro_batch_size: 4
  min_lr: 0.00005
  save_interval: 500
  tie_embeddings: true
